services:
  - docker
  - postgres
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/standup
before_install:
  - docker -v
  - docker-compose -v
install: make build
before_script:
  - psql -c 'create database standup;' -U postgres
script:
  - make test-image
notifications:
  irc: "irc.mozilla.org#standup"
